[package]
org = "anusankrishnathas"
name = "backend"
version = "0.1.0"
distribution = "2201.12.7"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerina"
name = "mongodb"
version = "5.1.0"
